FROM gitpod/workspace-full-vnc
RUN groupadd docker && \
    usermod -aG docker vscode && \
    sudo apt-get update && \
    sudo apt-get install -y libgtk-3-dev && \
    sudo rm -rf /var/lib/apt/lists/*
USER vscode